compliment_base = [
    "Champ, ",
    "Fact: ",
    "Everybody says ",
    "Dang...",
    "Check it: ",
    "Just saying...",
    "Superstar, ",
    "Tiger, ",
    "Know this: ",
    "News Alert: ",
    "Girl, ",
    "Ace, ",
    "Excuse me but ",
    "Experts agree: ",
    "In my opinion, ",
    "Hear ye, hear ye, ",
    "Okay, listen up: ",
    "Woah, okay, ",
    "I don't know if anyone's said this but ",
    "Oh my word, ",
    "Oh my ALANTA, "
]

compliment_subject = [
    "the mere idea of you " ,
    "your very SOUL ",
    "your hair today ",
    "everything you do ",
    "your personal style ",
    "every thought you have ",
    "that sparkle in your eye ",
    "your presence here ",
    "what you got GOING on ",
    "the essence of you ",
    "your life's journey ",
    "that saucy personality ",
    "that brain of yours ",
    "the way you roll ",
    "whatever your secret is ",
    "all of y'all "
]

compliment_descriptor = [
    "has serious game, ",
    "rains magic, ",
    "deserves the Nobel Peace Prize, ",
    "is a miracle, ",
    "is paying off BIG TIME, ",
    "shows mad skills, ",
    "just absolutely shines, ",
    "is a national treasure, ",
    "is the next big thing, ",
    "makes birds sing, ",
    "is like a precious diamond, ",
    "should be taught in school, ",
    "makes my world go 'round, ",
    "is 110\% legitness, ",
]

compliment_ending = [
    "24/7",
    "can I get an AMEN?",
    "and that's a fact.",
    "so treat yourself.",
    "you feel me?",
    "and that's just dope.",
    "for reals.",
    "and that's scientific FACT.",
    "~mic drop~",
    "you absolute gem.",
    "snuggle bear.",
    "PERIOD",
    "high five!",
    "so get used to it!",
]